- DEPENDENCIES
- package.json
- src/components/content/Cards/Card.tsx
- src/components/content/Cards/index.tsx
Fixed some incorrect type exports
Portal could not compile because of type conflict
n/a
> bugfix(types): fixed incorrect type exports

- DEPENDENCIES
- package.json
- scripts/release.sh
- src/index.ts
- src/theme.ts
App Marketplace Details not working in portal frontend
After switch to new library some values are not exported any more. This PR exports these values separately
JIRA: CPLP-2914
> bugfix(theme): some values not available in library

- package.json
- src/components/basic/StaticTable/HorizontalTable.tsx
Fix horizontal table for undefined values
Application threw an error when certain values where undefined
JIRA: CPLP-2914
> bugfix(table): fix display error for undefined values

- CHANGELOG.md
- src/components/basic/StaticTable/StaticTable.stories.tsx
- src/components/basic/StaticTable/VerticalTable.tsx
- src/components/basic/StaticTable/types.ts
- src/components/content/Cards/Card.tsx
Added condition for card(sub-menu) to fix coloring issue
To enhance.
Ref: CPLP-1552
> update(card): Added condition for card(sub-menu) to fix coloring issue

- .github/workflows/dependencies.yaml
- CHANGELOG.md
- DEPENDENCIES
- package.json
- yarn.lock
upgrade dependencies
address findings from security scan
n/a
> chore(dependencies): yarn upgrade

- .github/workflows/release.yml
- package.json
Write storybook build output to correct folder.
Build failed because output was not written to expected folder.
n/a
> bugfix(storybook): fix output folder for storybook

- CHANGELOG.md
- DEPENDENCIES
- package.json
- src/components/basic/SortOption/index.tsx
Fixed width for sort options(sub-menu)
For better look and feel.
NA
> update(sub-menu): width fix

- CHANGELOG.md
- DEPENDENCIES
- package.json
- yarn.lock
Upgrade dependencies
Switch to OSS safe eslint version
n/a
> chore(dependencies): upgrade eslint and other dependencies

- package.json
- src/components/basic/SelectList/index.tsx
change value attribute's value to selected instead of default value
Selected value is changing back to default value
NA
> bugfix(selectlist): selected value disappears

- DEPENDENCIES
- package.json
- src/components/basic/SelectList/index.tsx
update dependency file
build failure
NA
> bugfix(selected list): dependency failure

- CHANGELOG.md
- package.json
- src/components/basic/StaticTable/StaticTable.stories.tsx
- src/components/basic/StaticTable/VerticalTable.tsx
- src/components/basic/StaticTable/types.ts
Added column clickable if there is a existing link
Need to open new page
N/A
> feat(static table): add column clickable

- package.json
- src/components/basic/StaticTable/VerticalTable.tsx
- src/components/content/Cards/Card.tsx
- src/components/content/Cards/ContentCards.stories.tsx
Card Strip UI Changes
UI Enhancement
N/A
> feat(cards): status strip ui change

- package.json
- src/components/content/Cards/index.tsx
Added to card to center for better responsive
UI Enhancement
N/A
> feat(card responsive): added card to center

- package.json
- src/components/content/Cards/AppCards.stories.tsx
- src/components/content/Cards/Card.tsx
- src/components/content/Cards/index.tsx
Make card clickable 
Card clickable stopped working
n/a
> fix(card): card clickable fix

- package.json
- src/components/basic/Progress/LinearProgress/LinearProgressWithValueLabel.stories.tsx
- src/components/basic/Progress/LinearProgress/LinearProgressWithValueLabel.tsx
- src/components/index.tsx
Linear progress component with label and progress value
NA
NA
> feat(linear progress): new component

- src/components/content/Cards/CardAddService.tsx
Add new Card Height fix
UI enhancement
n/a
> fix(card): new card height fix

- package.json
- src/components/content/Cards/Card.tsx
- yarn.lock
Card Flag UI Changes
UI Enhancement
n/a
> fix(card): strip ui changes

- CHANGELOG.md
- package.json
- src/components/basic/ImageGallery/index.tsx
- src/components/basic/ImageGallery/types.ts
- src/components/basic/Progress/LinearProgress/LinearProgressWithValueLabel.tsx
- src/components/basic/StaticTable/StaticTable.stories.tsx
- src/components/basic/StaticTable/VerticalTable.tsx
- src/components/content/Cards/AppCards.stories.tsx
- src/components/content/Cards/Card.tsx
- src/components/content/Cards/index.tsx
- yarn.lock
Fixed sonar bugs
Improve efficiency
n/a
> bugfix(sonar): fix sonar bug

- DEPENDENCIES
- LICENSES/CC-BY-4.0.txt
- package.json
- src/assets/errorImage/robot-color.svg.license
- src/assets/errorImage/robot-sw.svg.license
- src/assets/logo/cx-logo-short.svg.license
- src/assets/logo/cx-logo-text.svg.license
- src/assets/logo/cx-logo.svg.license
- change license notice for images
- add second license
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07
n/a
> chore(trg-7-07): change license notice for images

- package.json
- src/components/basic/ErrorBar/ErrorBar.scss
- src/components/basic/ErrorBar/ErrorBar.stories.tsx
- src/components/basic/ErrorBar/ErrorBar.tsx
New error bar component with button to re trigger option
NA
NA
> feat(error bar): new component

- package.json
- src/components/index.tsx
export error bar component
export is missing
NA
> updates(error bar): export component

- .tractusx
- CHANGELOG.md
- package.json
- src/components/basic/Button/Button.test.tsx
- src/components/basic/DropdownMenu/index.tsx
- src/components/basic/Dropzone/index.tsx
- src/components/basic/Dropzone/types.ts
- src/components/basic/ImageGallery/ImageGalleryItem.stories.tsx
- src/custom.d.ts
- add file header
- update changelog
https://github.com/eclipse-tractusx/portal-shared-components/issues/39
> chore: add file header

- package.json
- src/components/basic/StaticTable/StaticTable.stories.tsx
- src/components/basic/StaticTable/VerticalTable.tsx
- src/components/basic/StaticTable/types.ts
Add info icon in table
To display info with field in statictable
n/a
> feat(static table): add icon in table with tooltip

- DEPENDENCIES
- SECURITY.md
update security.md
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01/#security-file
> docs: update security.md

- CHANGELOG.md
- DEPENDENCIES
- package.json
- src/components/basic/SubNavigation/ParentSubNavigation.tsx
- src/components/content/Cards/Card.tsx
Converted status condition to lowercase
To include active apps from service overview for sub-menu
Ref: CPLP-3181
> fix(card): status fix

- CHANGELOG.md
- package.json
- src/components/basic/Stepper/Stepper.stories.tsx
- src/components/basic/Stepper/StepperItem.tsx
- src/components/basic/Stepper/index.tsx
Changes in stepper component to add text and color to step
Need for an idp
n/a
> feat(idp): change idp stepper

- CHANGELOG.md
- src/components/basic/Dialog/Dialog.scss
- src/components/basic/Dialog/DialogActions.tsx
- src/components/basic/Dialog/DialogHeader.tsx
Dialog styles fix for header and actions
To enhance UI
Ref: CPLP-2807
> update(dialog): fix dialog styles

- package.json
package updated
package updated
Link to Github issue.
Ref: CPLP-2807
> update(package): package updated

- package.json
- src/components/basic/ToolTips/index.tsx
Add custom arrow css
UI enhancement
n/a
> feat(tooltip): add arrow css

- package.json
- src/components/basic/StaticTable/VerticalTable.tsx
StaticTable css help icon fix
UI Enhancement
n/a
> fix(statictable): help icon css fix

- CHANGELOG.md
- package.json
- src/components/basic/Table/PageLoadingTable.tsx
- src/components/basic/Table/components/Helper/helper.ts
- Update PageLoadingTable component with fetchArgs type
- Update helper file with the data types
- Remove content specific code. ex - bpnl
file has unwanted server specific logic
NA
> updates(pageLoadingTable): code cleaning

- .eslintrc.json
- CHANGELOG.md
- package.json
- src/components/basic/Progress/LinearProgress/LinearProgressWithValueLabel.tsx
- src/components/basic/StaticTable/VerticalTable.tsx
- src/components/basic/StaticTable/index.tsx
- src/components/basic/StaticTable/types.ts
- src/components/basic/Table/index.tsx
add types for imports
To remove lint errors
n/a
> feat(linter): add type for imports

- CHANGELOG.md
- package.json
- src/components/basic/ImageGallery/index.tsx
Added dynamic width and height
To enhance
Ref: CPLP-2811
> update(carousal): styles update

- CHANGELOG.md
- DEPENDENCIES
- package.json
- yarn.lock
Add dependencies to react-player and react-i18next
The libraries were missing in package.json which led to a warning in the build.
n/a
> bugfix(deps): add missing dependencies

- .eslintrc.json
- CHANGELOG.md
- DEPENDENCIES
- package.json
- src/components/basic/Breadcrumb/index.tsx
- src/components/basic/Carousel/CarouselBox.tsx
- src/components/basic/Carousel/index.tsx
- src/components/basic/Chip/TransitionChip.tsx
- src/components/basic/Chip/index.tsx
- src/components/basic/Datepicker/index.tsx
- src/components/basic/Dialog/index.tsx
- src/components/basic/ImageGallery/types.ts
- src/components/basic/LoadingButton/index.tsx
- src/components/basic/MultiSelectList/Components/SelectAddMore.tsx
- src/components/basic/MultiSelectList/index.tsx
- src/components/basic/OrderStatusButton/index.tsx
- src/components/basic/ProcessList/index.tsx
- src/components/basic/SelectList/index.tsx
- src/components/basic/SortOption/index.tsx
- src/components/basic/StaticTable/VerticalTable.tsx
- src/components/basic/Stepper/index.tsx
- src/components/basic/SubNavigation/ParentSubNavigation.tsx
- src/components/basic/Table/PageLoadingTable.tsx
- src/components/basic/Table/components/Helper/helper.ts
- src/components/basic/Table/index.tsx
Removing any type and adding particular type
code quality improvements
n/a
> updates(linters): removing any with particular type

- .eslintrc.json
- CHANGELOG.md
- DEPENDENCIES
- package.json
- src/components/basic/MultiSelectList/index.tsx
- src/components/basic/Notifications/Snackbar/PageSnackbarStack.tsx
- src/components/basic/SelectList/index.tsx
- src/components/basic/StaticTable/VerticalTable.tsx
- src/components/basic/StaticTable/types.ts
- src/components/content/DemoComponents/ContentComponentsTypes.ts
- src/components/content/DemoComponents/components/RenderImage.tsx
- src/components/content/DemoComponents/index.tsx
Fixing ban type linters as instead of empty object , add a particular type or unknown
new linter rule
n/a
> feat(linters): fixed ban types linters

- .eslintrc.json
- package.json
- src/components/basic/Menu/MenuItem.tsx
Remove extra semicolons to avoid linter warnings
linters fix
n/a
> update(linters): fix extra semicolons

- CHANGELOG.md
- DEPENDENCIES
- package.json
- yarn.lock
for @babel/traverse
CVE-2023-45133
> fix(vulnerability): set resolution

- .github/workflows/trivy.yml
- DEPENDENCIES
fix trivy: don't fail on high findings
action should only fail if there is an error/misconfiguration
relates to https://github.com/eclipse-tractusx/portal-frontend/pull/353
> fix(trivy): don't fail on high findings

- CHANGELOG.md
- DEPENDENCIES
- package.json
- src/components/basic/NewSubNavigation/NewSubNavigation.stories.tsx
- src/components/basic/NewSubNavigation/index.tsx
- src/components/basic/NewSubNavigation/styles.scss
- src/components/index.tsx
sub navigation which shows links and button in an overlay
new  change request
NA
> feat(component): new sub navigation

- CHANGELOG.md
- DEPENDENCIES
- package.json
- src/components/basic/StaticTable/StaticTable.stories.tsx
- src/components/basic/StaticTable/VerticalTable.tsx
- src/components/basic/StaticTable/types.ts
Add copy icon functionality in static table
Enhance the table to allow to copy the value
n/a
> feat(statictable): add copy icon value

- CHANGELOG.md
- DEPENDENCIES
- package.json
- src/components/content/UserMenu/index.tsx
enable position, width and shadow properties
multi device support
NALink to Github issue.
> fix(usermenu): extend props

- CHANGELOG.md
- package.json
- src/components/basic/Dialog/index.tsx
improve dialog style to support multi devices
support multi device
NA
> fix(dialog): fix style issue in tab and mobile view

- CHANGELOG.md
- package.json
- src/components/basic/CustomAccordion/CustomAccordion.stories.tsx
- src/components/basic/CustomAccordion/Item.tsx
- src/components/basic/CustomAccordion/index.tsx
Need close button in accordion
When user will click on close then open accordion will get closed
n/a
> feat(accordion): add action buttion in accordion

- CHANGELOG.md
- DEPENDENCIES
- package.json
- src/components/basic/OrderStatusButton/index.tsx
Order status button ui improvements
UI Enhancements as per figma
n/a
> feat(orderstatus button): ui changes

- CHANGELOG.md
- package.json
- src/components/basic/QuickLinks/QuickLinks.stories.tsx
- src/components/basic/QuickLinks/index.tsx
- src/components/index.tsx
Created new component 'quick links'
NA
Ref: CPLP-3436
> feat(quick links): new component quick links

- CHANGELOG.md
- package.json
- src/components/basic/QuickLinks/QuickLinks.stories.tsx
- src/components/basic/QuickLinks/index.tsx
Style(UI) fix for quick links
To enhance new component
Ref: CPLP-3436
> feat(quick links): style fix

- CHANGELOG.md
- package.json
- src/components/basic/QuickLinks/QuickLinks.stories.tsx
- src/components/basic/QuickLinks/index.tsx
Fix quick links interface types
To have valid names i interface
Ref: CPLP-3436
> fix(quick links): fix interface

- .github/workflows/release.yml
update node version
https://github.com/eclipse-tractusx/portal-cd/issues/158
> chore: update node version

- CHANGELOG.md
- package.json
- src/components/basic/QuickLinks/index.tsx
Fixed quick links styles
To achieve correct alignment for quick links
Ref: CPLP-3436
> fix(quick links): fix styles

- CHANGELOG.md
- package.json
- src/components/basic/OrderStatusButton/index.tsx
Height and text alignment width ui updates
UI alignments as per figma
n/a
> feat(order status button): ui changes

- CHANGELOG.md
- package.json
- src/components/basic/MultiSelectList/Components/SelectAddMore.tsx
- src/components/basic/MultiSelectList/index.tsx
Fixed multiselect search and selected items display issues
selected items are not displayed and page not visible on multiselect search
https://github.com/eclipse-tractusx/portal-frontend/issues/554
https://github.com/eclipse-tractusx/portal-frontend/issues/552
> fix(multiselect): fix search and select items display

- package.json
- src/components/basic/Dialog/DialogActions.tsx
- src/components/basic/Dialog/DialogHeader.tsx
- src/components/basic/Stepper/Stepper.scss
- src/components/basic/Stepper/Stepper.stories.tsx
Stepper and dialog ui updates
Need this UI changes in Portal registration validation pages
https://github.com/eclipse-tractusx/portal-frontend/issues/595
> feat(ui updates): stepper and dialog ui changes

- CHANGELOG.md
- package.json
- src/components/basic/CustomAccordion/Item.tsx
- src/components/basic/Stepper/Stepper.scss
- src/components/content/Cards/CardHorizontal.tsx
CSS changes
UI Enhancements
https://github.com/eclipse-tractusx/portal-frontend/issues/582
> feat(cleanups): ui Changes

- CHANGELOG.md
- DEPENDENCIES
- package.json
- yarn.lock
merge dependencies upgrades from dependabot
technical maintenance
na
> chore(dependabot): merge dependencies upgrades

- CHANGELOG.md
- DEPENDENCIES
- package.json
- src/components/basic/StaticTable/HorizontalTable.tsx
- src/components/basic/StaticTable/types.ts
- src/components/basic/Table/components/Toolbar/SearchAndFilterButtonToolbar.tsx
- src/components/basic/Table/components/Toolbar/SortImage/index.tsx
Add copy icon and functionality to horizontal table
To enhance horizontal table to have copy functionality
https://github.com/eclipse-tractusx/portal-frontend/issues/743
> feat(horizontal table): add copy function

- CHANGELOG.md
- package.json
- src/components/basic/Progress/CircleProgress/index.tsx
- src/components/basic/StaticTable/EditField.tsx
- src/components/basic/StaticTable/VerticalTableNew.tsx
- src/components/index.tsx
expose size attribute
new request
https://github.com/eclipse-tractusx/portal-frontend/issues/697
> fix(refactor): expose size attribute in circular progress component

- CHANGELOG.md
- package.json
- src/components/basic/Button/ScrollToTopButton.tsx
move css from front end repo to component file
NA
https://github.com/eclipse-tractusx/portal-frontend/issues/675
> fix(scroll to top): update style

- .github/workflows/checks.yml
- DEPENDENCIES
add workflow_dispatch to pr checks workflow
to be able to trigger the workflow manually
> chore(pr checks): add workflow_dispatch

- CHANGELOG.md
- docs/storybook/button.md
- docs/storybook/datepicker.md
- docs/storybook/selectlist/dropdown.md
- package.json
Updated images for markdown files
To display images in storybook
3340
> feat(docs): update images

- CHANGELOG.md
- DEPENDENCIES
- package.json
- src/components/index.tsx
export select input and sort option components
new request
NA
> feat(select): export components

- src/components/content/Cards/AppCards.stories.tsx
- src/components/content/Cards/CardAddService.stories.tsx
- src/components/content/Cards/CardAddService.tsx
- src/components/content/Cards/CardContent.tsx
- src/components/content/Cards/index.tsx
- **New Prop (showCardView):**  
Added a `showCardView` prop to toggle between a card element and full-screen view version.
- **Padding & Width Adjustments:**  
Added padding and adjusted width to enhance layout consistency and visual alignment in the grid.
- **Text Overflow Handling:**  
Fixed issues with large text causing layout breaks by using the correct `line-clamp` property to manage text overflow effectively.
The following images demonstrate the differences before and after the modifications in padding, width, and text overflow handling:
**Before Padding & Width Adjustment**  
**After Padding & Width Adjustment**  
**Before Text Overflow Handling**  
**After Text Overflow Handling**  
- Fix Subtitle and Title Text Overlapping Issue
**Before**  
**After**  
- We can remove the …
> fix: update 'add service card' design & add app card variant in storybook

- DEPENDENCIES
- src/components/basic/Dialog/Dailog.mdx
add mdx file  for Dialog/Modal component.
demonstrate how to use header, content and action buttons
NA
#232 
> fix(dialog): add mdx file to the dialog component

- CHANGELOG.md
- DEPENDENCIES
- package.json
- src/components/basic/ToggleSwitch/ToggleSwitch.scss
- src/components/basic/ToggleSwitch/ToggleSwitch.stories.tsx
- src/components/basic/ToggleSwitch/index.tsx
Need to implement a new toggle switch component that adheres to our design system.
The toggle switch should be used when a user needs to perform an action that will turn a feature or setting on or off
https://github.com/eclipse-tractusx/portal-shared-components/issues/254
> feat(toggle switch): implement new toggle switch design

- CHANGELOG.md
- package.json
- src/components/basic/Table/components/Toolbar/index.tsx
- src/components/basic/Table/index.tsx
add new props to support multiple buttons in table component
handle multiple buttons
NA
> fix(table): support buttons props

- src/components/basic/Table/PageLoadingTable.tsx
* Implemented infinite scroll for the `PageLoadingTable` component.
* Removed the 'Load More' button.
* Added a loading spinner for data fetches.
* Displayed a message when all items are loaded.
* Improves user experience by loading data on scroll.
* Provides better feedback with a loading spinner and completion message.
[286](https://github.com/eclipse-tractusx/portal-shared-components/issues/286)
> feat: infinite scroll for page loading table

- package.json
Release 3.6.0
Includes new features for portal frontend
n/a
> chore: release 3.6.0

- DEPENDENCIES
- package.json
- src/components/basic/BaseImage/index.tsx
- yarn.lock
Upgrade dependent libraries
Regular procedure to get latest bug fixes.
#320
> chore: upgrade lib dependencies

- package.json
Bump version to trigger release 3.7.0
Fixes, upgrades and new features have been merged.
n/a
> chore: bump version to 3.7.0

- package.json
Bump the version to 3.7.4
This is to trigger the release please flow to create a new release.
n/a
> build: bump version to 3.7.4

- package.json
Bump version to 3.7.6
Trigger release workflow
n/a
> chore: bump version to 3.7.6

- package.json
Bump version to 4.0.0
Trigger release workflow following [release-process.md](https://github.com/eclipse-tractusx/portal-shared-components/blob/main/docs/admin/release-process/release-process.md)
n/a
> chore: bump version to 4.0.0

- package.json
Bump version to 4.0.2
Trigger release workflow following [release-process.md](https://github.com/eclipse-tractusx/portal-shared-components/blob/main/docs/admin/release-process/release-process.md)
n/a
> chore: bump version to 4.0.2
