.github/workflows/dependencies.yaml
DEPENDENCIES
scripts/check-dependencies.md

- add workflow to check 3rd party dependencies with the [Eclipse Dash License Tool](https://github.com/eclipse/dash-licenses)
run with  dependencies file not changed: https://github.com/eclipse-tractusx/portal-backend/actions/runs/5375054212/jobs/9751059140
example run with dependencies file changed (repurposed unit testing und formatting workflow for testing): https://github.com/eclipse-tractusx/portal-backend/actions/runs/5374531262/jobs/9749999098
- change dependencies file to '-summary' format from Dash Tool
**Due to the new format in the dependencies file: once this PR is merged into dev, all open feature branches should be rebased to dev, as the dependencies check will fail otherwise.**
Dependencies check should be automated.
n/a

chore: add workflow to check dependencies

---

.github/workflows/dependencies.yaml
DEPENDENCIES
scripts/check-dependencies.md

change dash tool version
1.0.3-SNAPSHOT did fail in portal-frontend, due to that change to a more stable version
n/a

chore: change dash tool version

---

.github/workflows/release.yml

Add storybook build and publish to workflow
Storybook should be published on GitHub pages on every release
Jira: CPLP-2913

chore(storybook): add storybook build and publish to workflow

---

.github/workflows/release.yml
CHANGELOG.md
README.md
package.json

Enable storybook build and publish
This step was prepared and is now activated after GitHub pages have been enabled.
ref. Jira CPLP-2913

feat(storybook): enable storybook publish in release workflow

---

.github/workflows/release.yml

Enable manual workflow dispatch and trigger on package.json
Sometimes a manual trigger is needed and we don't need dummy commits. Also a package.json update should trigger the release because it may have an impact on the built artifacts.
n/a

chore(build): enable workflow dispatch

---

CHANGELOG.md
package.json
src/components/basic/ErrorBar/ErrorBar.scss
src/components/basic/ErrorBar/ErrorBar.stories.tsx
src/components/basic/ErrorBar/ErrorBar.tsx
src/components/basic/StaticTable/StaticTable.stories.tsx
src/components/basic/StaticTable/VerticalTable.tsx
src/components/basic/Stepper/Stepper.stories.tsx
src/components/basic/Stepper/StepperItem.tsx
src/components/content/Cards/CardImage.tsx

Enable custom image elements on cards
We also like to support the option to render already loaded images on cards.
Some formatted files also added.
ref. Jira CPLP-3190

feat(cards): enable custom image element

---

CHANGELOG.md
package.json
src/components/content/Cards/index.tsx

Add an optional image element to cards
Developers can add an optional image item to cards.
ref: Jira CPLP-3190

feat(cards): add image element to cards

---

CHANGELOG.md
DEPENDENCIES
package.json
src/components/basic/Datepicker/index.tsx
yarn.lock

Migrate date picker component from mui to the latest v6.
During the yarn upgrade some libraries could not be upgraded to latest version because of breaking changes: So upgrading now
NA

upgrade(date picker): migrate to v6

---

CHANGELOG.md
DEPENDENCIES
package.json
src/components/basic/Table/index.tsx
src/components/basic/Table/table.stories.tsx
yarn.lock

Migrate data grid component from mui to the latest v6.
During the yarn upgrade some libraries could not be upgraded to latest version because of breaking changes: So upgrading now
NA

upgrade(data grid): migrate to v6

---

CHANGELOG.md
DEPENDENCIES
package.json
src/components/basic/Table/components/Toolbar/SearchAndFilterButtonToolbar.tsx
src/components/basic/Table/components/Toolbar/UltimateToolbar.tsx
src/components/basic/Table/components/Toolbar/index.tsx

Technical Improvement: Search Element (active search & delete icon)
Search Element Improvements
n/a

feat(table): search element improvements

---

CHANGELOG.md
DEPENDENCIES
package.json
src/components/basic/Stepper/Stepper.scss
src/components/basic/Stepper/Stepper.stories.tsx
src/components/basic/Stepper/StepperItem.tsx
src/components/basic/Stepper/index.tsx

Add tooltip in stepper
Need for registration stepper in portal
n/a

feat(stepper): add tooltip in stepper

---

CHANGELOG.md
package.json
src/components/basic/Image/index.tsx

When an image loader is specified use it directly
When the image component has an image url and a loader specified it tries to display the image URL directly first and only in case of an error is using the loader which can result in a loading error plus delayed loading time. With this fix we always use the loader directly when one is specified.
ref: Jira CPLP-3190

fix(image): render image with loader when specified

---

CHANGELOG.md
DEPENDENCIES
package.json
src/components/basic/Image/index.tsx

Fix a bug that caused infinite React re-renders.
A previous change in the image component introduced this bug that could lead to a blank window. This PR fixes that bug.
ref: Jira CPLP-3190

fix(image): fix rerender bug

---

.github/pull_request_template.md
CHANGELOG.md
DEPENDENCIES
package.json
src/components/basic/Image/Image.stories.tsx
src/components/content/DemoComponents/CardGrid.stories.tsx
src/components/content/DemoComponents/FlexImages.stories.tsx
src/components/content/DemoComponents/GridImages.stories.tsx
yarn.lock

- upgrade node-ip package (transitive dependency over @storybook/core-server) to remove CVE-2023-42282
- remove catenax-ng picture references
- pr-template: fix link to contributing guidelines 
security and chores
na

chore: remove CVE-2023-42282 and catenax-ng picture references

---

CHANGELOG.md
package.json
src/components/basic/Table/PageLoadingTable.tsx
src/components/basic/Table/components/Helper/helper.ts

update the condition to show more button based on the data available
more button is not visible
[#439](https://github.com/eclipse-tractusx/portal-frontend/issues/439)

fix(page loading): condition for more button

---

CHANGELOG.md
package.json
src/components/basic/Table/components/Helper/helper.ts
src/components/basic/Table/components/Toolbar/SearchAndFilterButtonToolbar.tsx
src/components/basic/Table/components/Toolbar/UltimateToolbar.tsx
src/components/basic/Table/components/Toolbar/index.tsx
src/components/basic/Table/index.tsx

add autoFocus as a new prop and provide true as default value
autoFocus is creating issues of unhelpful scroll in several pages.
https://github.com/eclipse-tractusx/portal-frontend/issues/431

feat(table): add autoFocus as new props

---

CHANGELOG.md
package.json
src/components/basic/Dropzone/components/DropPreview.tsx

complete string escaping and encoding in DropPreview
security finding
https://github.com/eclipse-tractusx/portal-cd/issues/197

fix(DropPreview): complete string escaping and encoding

---

.tractusx
NOTICE.md

change portal-cd references to portal
TRG-2.04 compliance
https://github.com/eclipse-tractusx/portal-cd/issues/131

chore(trg-2.04): change portal-cd references to portal

---

CHANGELOG.md
package.json
src/components/content/Cards/Card.tsx
src/components/content/Cards/CardDecision.tsx
src/components/content/Cards/index.tsx

Fixed properties written in kebap-case where camelCase is required
In the browser dev tools we got an ugly warning message which is removed now.
n/a

fix(css): fix misspelled properties

---

CHANGELOG.md
package.json
src/components/basic/Image/index.tsx

Use image loader first if specified
The image component always tried to display the src url first which resulted in a lot of failure messages on the console in case the src url needed authentication. Now the logic has been reversed and if a loader function is specified this will be invoked first. This reduces the number of request and the console looks cleaner.
ref Jira: CPLP-3243, -3244, -3273

fix(image): use image loader first if specified

---

.github/dependabot.yml
.github/workflows/checks.yml
.github/workflows/dependencies.yaml
.github/workflows/kics.yml
.github/workflows/pullRequest-lint.yaml
.github/workflows/release.yml
.github/workflows/trivy.yml
CONTRIBUTING.md
DEPENDENCIES
scripts/check-dependencies.md

- upgrade gh actions and change to pinned actions full length commit sha
- docs(CONTRIBUTING.md): link to contribution details
- chore: add dependabot.yml file
https://github.com/eclipse-tractusx/portal/issues/225
https://github.com/eclipse-tractusx/portal/issues/219
https://github.com/eclipse-tractusx/portal-frontend/issues/566

chore: upgrade gh-actions and docs

---

CHANGELOG.md
package.json
src/components/basic/SortOption/index.tsx
src/components/content/Cards/Card.tsx
src/components/content/Cards/MarketplaceCard.stories.tsx
src/components/content/Cards/index.tsx

Added submenu options for active and inactive cards
To enhance inactive cards with submenu
https://github.com/eclipse-tractusx/portal-frontend/issues/581

fix(cards): add submenu options

---

CHANGELOG.md
package.json
vite.config.ts

Generate .d.ts files for use in typescript
Due to a recent rename of the src folder the typescript definition files were not generated correctly.
n/a

fix(types): generate types for typescript

---

.github/workflows/dependencies.yaml
CHANGELOG.md
package.json
scripts/check-dependencies.md

add step to dependencies check to download eclipse dash tool instead
the jar leads continuously to an unnecessary long IP check, example https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14240
na

chore: remove eclipse dash tool jar

---

CHANGELOG.md
package.json
src/components/content/Cards/CardHorizontal.tsx
src/components/content/Cards/index.tsx

Keep some props removed during framework upgrade
During the framework upgrade some props were removed after the typescript compiler showed them as obsolete. However we keep them for backward compatibility
#147

fix(compatibility): re-introduce props

---

CHANGELOG.md
package.json
src/components/basic/NewSubNavigation/index.tsx

show sub navigation to the user on hover to the dots/sub navigation header title
sub navigation is blocking user to access other section in smaller browser
#759

fix(sub navigation): show sub navigation contents on mouse hover

---

CHANGELOG.md
package.json
src/components/basic/StaticTable/VerticalTable.tsx

Fixed editing input field in vertical table
To make editing the input field possible in vertical table,
https://github.com/eclipse-tractusx/portal-frontend/issues/775

fix(vertical table): fixed editing input field in vertical table

---

CHANGELOG.md
package.json
src/components/basic/CustomAccordion/Item.tsx

Change background color on hover and focus
If color exists then it should take given color otherwise default color will be assigned on hover/focus
https://github.com/eclipse-tractusx/portal-frontend/issues/803

feat(custom accordion): change background color on hover and focus

---

CHANGELOG.md
package.json
src/components/basic/StaticTable/HorizontalTable.tsx
src/components/basic/StaticTable/VerticalTable.tsx

Change default color and on hover color of copy icon in static table
To enhance the look and feel of the copy icon in static table
NA

fix(static table): fix copy icon color 

---

.github/dependabot.yml
.github/workflows/checks.yml
.github/workflows/codeql.yml
.github/workflows/dependencies.yaml
.github/workflows/kics.yml
.github/workflows/pullRequest-lint.yaml
.github/workflows/release.yml
.github/workflows/trivy.yml
.husky/pre-commit
CHANGELOG.md
DEPENDENCIES
README.md
package.json
yarn.lock

Add a pre-commit hook to format and lint staged files
The pre-commit hook does two things to improve the quality of code committed:
- format all staged files with prettier before going into the commit
- lint all staged source files and cancel the commit on errors
Additionally we added yaml files to the prettier.
n/a

feat: add pre-commit hook

---

.husky/pre-commit
CHANGELOG.md
DEPENDENCIES
package.json
yarn.lock

Reduce dependencies and add unit tests
lint-staged comes with many dependencies and the tool is only used on developer machines. We removed it from project dependencies and execute it from husky through npx avoiding the download of many packages on every pipeline run. Also unit tests are now executed on staged files if present.
n/a

chore(husky): improve pre-commit hook

---

CHANGELOG.md
package.json
src/components/basic/Table/components/Error/Error400Overlay.tsx
src/components/basic/Table/components/Error/Error500Overlay.tsx
src/components/basic/Table/index.tsx

Updated table component to support error messages
to enhance table component to support error messages
https://github.com/eclipse-tractusx/portal-frontend/issues/891
https://github.com/eclipse-tractusx/portal-frontend/issues/888

feat(table): update table to support error messages

---

CHANGELOG.md
package.json
src/@types/chip.ts
src/@types/styles.ts
src/components/basic/Table/components/StatusTag/index.tsx
src/theme.ts

updated status tag color and also updated theme and chip with 'deleted' property
To add color for status 'deleted'
https://github.com/eclipse-tractusx/portal-frontend/issues/944

feat(status tag): update status tag color

---

CHANGELOG.md
package.json
src/components/basic/SelectList/index.tsx

- The SelectList component, part of the application's user interface for selecting items from a dropdown list, experienced an issue where the selected Sales Manager was not saved upon submitting the App Card Details. This component leverages the Autocomplete component from Material-UI to provide auto-suggestions and a user-friendly selection process.
- Users reported that after selecting a Sales Manager from the dropdown list and submitting the App Card Details, the selected Sales Manager was not saved. This led to the Sales Manager information being lost, resulting in incomplete data submission and potential disruptions in the workflow.
This change is necessary to address a critical issue where the `SelectList` component does not save the selected values upon form submission, or resets …

fix: Selected Values Not Saved or Reset to Default in SelectList Component

---

CHANGELOG.md
package.json
src/components/basic/SelectList/index.tsx

- With ref to this PR https://github.com/eclipse-tractusx/portal-shared-components/pull/257, we need to update the condition in handleChange function so that component should update the value prop/selected value
This change is necessary to address a critical issue where the `SelectList` component does not save the selected values upon form submission, or resets them to the default values. This issue affects the data integrity and user experience, as users expect their selections to be retained and accurately reflected in the submitted data.
- **Data Integrity**: Ensuring that the selected values are correctly saved prevents data loss and maintains the integrity of the information submitted by the users.
- **User Experience**: Users need to trust that their selections are preserved. Losing …

fix: handleChange function causing issue while selecting values from selectList component

---

CHANGELOG.md
src/components/basic/ImageGallery/ImageItemOverlay.tsx
src/components/basic/ImageGallery/index.tsx

- This PR addresses the issue where clicking on app images in the "App Details" page results in a `401 Unauthorized` error.
- **Bug Fix:** Resolved the `401 Unauthorized` error that occurred when users clicked on app images in the "App Details" page.
- This issue was causing unauthorized errors, disrupting the user experience. Fixing this will ensure that users can interact with app images without encountering access issues.
[#291
](https://github.com/eclipse-tractusx/portal-shared-components/issues/291)

fix: Fix 401 Unauthorized Error on App Image Click in App Details

---

CHANGELOG.md
src/components/basic/ImageGallery/index.tsx

- The user uploads one image on the App details page while registering the app but it ended up showing the same image 3 times. Since max 3 images can be uploaded, the system somehow repeats the image thrice.
- One single image repeat thrice on the Validate & Publish screen as well as on the App overview page.
- Image should display only once on both the Validate & Publish screen as well as on the App overview page.
- Shared Component: [#288](https://github.com/eclipse-tractusx/portal-shared-components/issues/288)
- Portal Frontend: [#1031](https://github.com/eclipse-tractusx/portal-frontend/issues/1031)

fix: Resolve App details image duplications

---

DEPENDENCIES
src/components/basic/Carousel/index.tsx

Component: Carousel
- Modified the infinite setting, in case of single children is passed into component.
The carousel component is rendering incorrect UI with cloned elements when
-  `infiniteScroll` is set to `true` &
-  Single child element is passed
#292 

fix(carousel): handle infinite scroll with a single child element

---

package.json
src/components/basic/ToggleSwitch/ToggleSwitch.scss
src/components/basic/ToggleSwitch/ToggleSwitch.stories.tsx
src/components/basic/ToggleSwitch/index.tsx

Need to remove default text from tooltipText and ui issue need to fix on hard reload.
Default tooltip text not needed and ui should be consistent on hard reload
https://github.com/eclipse-tractusx/portal-shared-components/issues/254

fix(new toggle switch): default text removed and ui issue fixed

---

src/components/basic/Dialog/index.tsx
src/components/basic/Dropzone/components/DropPreviewFile.tsx
src/components/basic/ImageGallery/types.ts
src/components/basic/MultiSelectList/index.tsx
src/components/basic/SelectList/index.tsx
src/components/basic/Table/PageLoadingTable.tsx
src/components/basic/Table/index.tsx

- **Replaced `any` Type**: Updated the code to use specific types instead of `any`.
- **Removed ESLint Comments**: Deleted unnecessary `eslint-disable-next-line` comments that were bypassing type-related linting rules.
- Replacing `any` type with specific types improves type safety, helps catch errors early, and makes the code easier to read and maintain.
[311](https://github.com/eclipse-tractusx/portal-shared-components/issues/311)

refactor: remove use of 'any' type

---

DEPENDENCIES
package.json
src/components/basic/ToggleSwitch/index.tsx

Removed the on off text from toggle switch
On and Off text not required any more from demo feedback
https://github.com/eclipse-tractusx/portal-shared-components/issues/254

fix(new toggle switch): remove the on off text

---

docs/README.md
docs/admin/release-process/release-process.md

Adjust documentation structure to align with TRG1
To align document structure with TRG 1
#315

docs: align doc structure with TRG1

---

.prettierignore

release please uses * for lists, prettier wants -, as the changelog is autogenerated since https://github.com/eclipse-tractusx/portal-shared-components/pull/263, I'd just exclude it from the prettier check
prettier check fails, example PR https://github.com/eclipse-tractusx/portal-shared-components/pull/329
n/a

chore(prettier-check): ignore changelog

---

src/components/content/Cards/Card.tsx
src/components/content/Cards/CardContent.tsx

Card component wasn't handling longer text description gracefully and some Label and typography elements spaces wasn't consistent to look appealing. I implemented some new css properties to make longer text transition in truncate and introduced margin around text elements.
The longer text cause broken UI and user can't read the rest of the information which was coming beneath the card component.
After fix:
https://github.com/eclipse-tractusx/portal-shared-components/issues/335

fix(UI): card component spaces

---

src/components/content/Cards/CardChip.tsx

Convert status value to lowercase.
To fix this issue : Service overview shows only greyed out status labels
[#1231](https://github.com/eclipse-tractusx/portal-frontend/issues/1231)
#308

fix: convert status to lowerCase

---

DEPENDENCIES
src/components/content/Cards/CardDecision.stories.tsx
src/components/content/Cards/CardDecision.tsx

- Added a statusText props to display text in chips
- Some text like **In Review** is getting displayed like this **IN_REVIEW**
- ![image](https://github.com/user-attachments/assets/956b71e9-b7e4-40b2-be74-fcbc23405eae)
- https://github.com/eclipse-tractusx/portal-shared-components/issues/352

fix: add statusText props in cardDecision to have proper text in chips

---

CHANGELOG.md
src/components/content/Cards/CardHorizontal.stories.tsx
src/components/content/Cards/CardHorizontal.tsx

Removed the Box element for the image inside HorizontalCard component and replaced with Image component. 
HorizontalComponent should have the logic to handle the loader function and other properties similarly like we already have in Card Componet as an example.
https://github.com/eclipse-tractusx/portal-shared-components/issues/356

feat: added image object in horizontal card component

---

.github/workflows/dependencies.yaml

- Modify dependencies check to run only on yarn.lock updates
- Reduce unnecessary runs by triggering dependency checks only when yarn.lock changes.
- https://github.com/orgs/eclipse-tractusx/projects/61/views/1?pane=issue&itemId=86504502
#382

ci: modify dependencies check to run only on yarn.lock updates

---

src/components/basic/Table/index.tsx

- The Table component includes a search bar to filter results. However, users were unable to clear the search text after entering it without refreshing the page.
- The search bar is integrated within the Toolbar component, where the `onClearSearch` method is implemented. However, the method was not being correctly passed down from the parent component, preventing it from functioning as expected.
- Ensured that the onClearSearch method is properly passed from the parent component to enable text clearing in the search bar without needing a page refresh.
- https://github.com/eclipse-tractusx/portal-shared-components/issues/370
```
- **App & Service Subscription**:
- Fixed issue preventing search text from being cleared in App & Service Subscription without a page refresh. …
```

fix(app & service subscription): fix search text clearing

---

src/components/basic/Input/Input.mdx
src/components/basic/Input/index.tsx

input element has been modified to be used as masked input component as well when needed.
we currently have all secrets readable and we want to by default make them masked , along side giving user the right to toggle the view.
[Link to Github issue.](https://cofinity-x.atlassian.net/browse/CS-2498)

chore: input component modified to be used as masked input as well

---

src/components/basic/CategoryDivider/index.tsx
src/components/basic/StaticTable/style.scss

Fixes removing react warnings
Implementation flaws caused warnings in dev mode
[portal-frontend #1269](https://github.com/eclipse-tractusx/portal-frontend/issues/1269)

fix(react): replace first-child pseudo class

---

docs/admin/release-process/release-process.md

add NPM_PUBLISH token configuration section to release process
proper documentation was missing
Refs: #436

docs: add NPM_PUBLISH token info to release process
